// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AnswerForm: typeof import('./src/components/AnswerForm.vue')['default']
    AnswerItem: typeof import('./src/components/AnswerItem.vue')['default']
    Charts: typeof import('./src/components/Charts.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    PoolForm: typeof import('./src/components/PoolForm.vue')['default']
    Survey: typeof import('./src/components/Survey.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
  }
}

export { }
